# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1947e135e93a890707205dde770a791b403bc8aa38fa255e6b1361884e010d3feb3343f9943d5d504718d9544a4be8b318ea36e89964fa655a7c691b73f47648

test:
  secret_key_base: a8e70e451fe3abd27d1cc5e6eff6ccc7376200d8cfd9681516aa09f38379c91499a99966f48d0d36021cb13d84b81139cef0246ea14ff011af64cbf431cfccae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
